name: music_app
description: Aplicación para BariberMusic&Spa

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0      # Cliente HTTP potente con buenas características
  http: ^1.2.1
  json_annotation: ^4.8.1  # Para serialización de JSON
  provider: ^6.0.5
  font_awesome_flutter: ^10.8.0
  video_player: ^2.8.0
  chewie: ^1.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1  # Para generación de código
  build_runner: ^2.4.8       # Para ejecución de generadores de código

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/services/corte.png
    - assets/services/masaje.png
    - assets/videos/banner_home.mp4