name: music_app
description: BarberMusic & Spa Flutter application

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  go_router: ^12.1.1
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  flutter_dotenv: ^5.0.2
  image_picker: ^1.0.7
  video_player: ^2.8.2
  chewie: ^1.7.5
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/services/
    - assets/videos/
