name: music_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  go_router: ^12.1.3
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  video_player: ^2.8.7
  chewie: ^1.11.3
  webview_flutter: ^4.7.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.3.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/services/
    - assets/videos/
