// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
import 'firebase_options.dart';
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4huETd2yIEOkR_39kegM-UXagSQFWAU',
    appId: '1:555326180608:android:1356b78c94076449a6b7e5',
    messagingSenderId: '555326180608',
    projectId: 'musicapp-8d009',
    storageBucket: 'musicapp-8d009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--iDVhOB5gL7qq6x6sLOnTstMhkfbO0E',
    appId: '1:555326180608:ios:8aa502fcb8c1dd6fa6b7e5',
    messagingSenderId: '555326180608',
    projectId: 'musicapp-8d009',
    storageBucket: 'musicapp-8d009.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC--iDVhOB5gL7qq6x6sLOnTstMhkfbO0E',
    appId: '1:555326180608:ios:8aa502fcb8c1dd6fa6b7e5',
    messagingSenderId: '555326180608',
    projectId: 'musicapp-8d009',
    storageBucket: 'musicapp-8d009.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4BSSx9VHxgWxEoyeNzyimiGAcXzLcpJc',
    appId: '1:555326180608:web:abac2f0f5eba6abfa6b7e5',
    messagingSenderId: '555326180608',
    projectId: 'musicapp-8d009',
    authDomain: 'musicapp-8d009.firebaseapp.com',
    storageBucket: 'musicapp-8d009.firebasestorage.app',
    measurementId: 'G-NEWTN1E17X',
  );
}
